#!/usr/bin/env bash
echo -en '\e[?1049h'
stty -icanon -echo -isig -ixon -ixoff
echo -en '\e[?25l'
(hash java7 2>/dev/null)
if [ $? = 0 ]; then
    java7 -jar "$0".jar `stty size` "$@"
else
    java -jar "$0".jar `stty size` "$@"
fi
rc=$?
echo -en '\e[?25h'
stty icanon echo isig ixon ixoff
echo -en '\e[?1049l'
exit $rc
